spring:
  profiles:
    active: local
    include: aws

# logging 설정
logging:
  level:
    root: INFO
    sql: debug # org.hibernate.SQL은 logger를 통해 하이버네이트 실행 SQL을 남긴다.
    org:
      hibernate:
        type:
          descriptor:
            sql: info
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

github:
  client-id: 8f285a7d51cbddc39104
  client-secret: a25c4a9fab910f206855eea684be46f0bb457d60
  redirect-url: http://15.164.35.235/api/github/oauth/callback
  access-token-request-url: https://github.com/login/oauth/access_token
  email-request-url: https://api.github.com/user/emails
